name: Build and publish

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
jobs:
  image-publish:
    runs-on: self-hosted
    outputs:
      changed_files: ${{ steps.changes.outputs.changed_files}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builder

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: docker-proxy.devops.projectronin.io/tonistiigi/binfmt:latest

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          endpoint: builder
          driver-opts: image=docker-proxy.devops.projectronin.io/moby/buildkit:v0.10.6

      - name: Login to Repo
        run: |-
          docker login \
          -u "${{secrets.NEXUS_DOCKER_USERNAME}}" \
          -p "${{secrets.NEXUS_DOCKER_PASSWORD}}" \
          ${{ vars.DOCKER_WRITE_REPO }}

      - name: Get image tag
        id: get_image_tag
        run: |-
          echo "============================ TAGS ==============================="
          git tag
          echo "================================================================="
          TAG=$(git describe --tags)
          echo "tag=${TAG}" >> "$GITHUB_ENV"
          if [[ ${REF_TYPE} == "tag" ]]; then
            SECOND_TAG_PREFIX="--tag"
            SECOND_TAG=${{ vars.DOCKER_WRITE_REPO }}/ronin-contract-rest-tooling:v$(echo "${TAG}" | perl -p -e 's/^v?([0-9]+)\..*$/$1/g')
          else
            SECOND_TAG_PREFIX=""
            SECOND_TAG=""
          fi
          echo "second_tag=${SECOND_TAG}" >> "$GITHUB_ENV"
          echo "second_tag_prefix=${SECOND_TAG_PREFIX}" >> "$GITHUB_ENV"
        env:
          REF_TYPE: ${{ github.ref_type }}
          REF_NAME: ${{ github.head_ref || github.ref_name }}

      - name: Build and push main branch images
        run: |-
          docker build --platform linux/amd64,linux/arm64 --push --tag ${{ vars.DOCKER_WRITE_REPO }}/ronin-contract-rest-tooling:${{ env.tag }} ${{ env.second_tag_prefix }} ${{ env.second_tag }} .
        working-directory: ./
